### ISSUE TITLE
@require jquery not working with latest version

### ISSUE THREAD

**Issue by R0bb12** [derjanb/tampermonkey#210]
My user script stop working on 10 April 2015, with the latest version of Tampermonkey 3.10.84 and Chrome 41

I'm using @require with local or web version of latest jquery 2
Script work without @require jquery, but I need it.
Work very well since 1 year on Chrome and Firefox

Here a test script
// ==UserScript==
// @name           test
// @version    	   1.0
// @include        /^http://.*$/
// @author         Robin
// @description    test
// @require        jquery/jquery-2.1.3.min.js
// ==/UserScript==

alert("toto");

Producing log like this in chrome debug console
Syntax error @ 'test'!
##########################
JSHINT output:
require: (W033) Missing semicolon on line: 3 at character: 205
require: (W030) Expected an assignment or function call and instead saw an expression on line: 3 at character: 210
require: (W033) Missing semicolon on line: 3 at character: 211
require: (W033) Missing semicolon on line: 3 at character: 423
require: (W033) Missing semicolon on line: 3 at character: 529
require: (W033) Missing semicolon on line: 3 at character: 631
require: (W041) Use '!==' to compare with 'null' on line: 3 at character: 660
require: (W033) Missing semicolon on line: 3 at character: 708
...

**Comment by derjanb** [comment]
What is the install URL of that script? You're requiring JQuery from a URL relative to the install URL.

http://wiki.greasespot.net/Metadata_Block#.40require

**Comment by R0bb12** [comment]
It's installed from a custom local repository.
The repository allow installing and updating user script on local enterprise network, to users who do not have access to internet (so every @require target a local file).
User script works on intranet sites.
User script are correctly installed and updated on Chrome and Firefox from that repository.
User script only works on FireFox, not on Chrome from that repository.

Before I setup the repository, user script were installed by hand (local copy on computer, then drag and drop on tampermonkey), works well. Maybe jquery was corrupted during installation from repository?

**Comment by derjanb** [comment]
Sounds reasonable. You can force a refresh by opening the script, then selecting its "Externals" tab and pressing the "Delete" button at the JQuery require.

**Comment by R0bb12** [comment]
According to tampermonkey, on external view, jquery size is twice the real size.

**Comment by derjanb** [comment]
The size should match the real size. So probably something went wrong when the require was updated the last time. 
Have you tried to delete it? For testing you can also replace the old require with:
'''@require http://code.jquery.com/jquery-2.1.3.min.js'''

**Comment by R0bb12** [comment]
Work with online jquery but not from my repository, it gave me:
URL	http://localhost:5528/api/file/test/jquery/jquery-2.1.3.min.js
Size	163840 Bytes
Dernière mise à jour	Tue Apr 14 2015 13:24:21 GMT+0200 (Paris, Madrid (heure d’été))

Size is 163840 instead of 84320. Will do some check

**Comment by R0bb12** [comment]
By the way, others js have the wright size, only jquery is too fat

**Comment by R0bb12** [comment]
Ok, for an unknown reason my repo add lot of bad bytes at the end of jquery file.
So it's not a tampermonkey issue.
Anyway, thanks for your help.
