### ISSUE TITLE
i cannot  find “Tamper Fire”  opition

### ISSUE THREAD

**Issue by vicliu1990** [derjanb/tampermonkey#212]
i an using  the  lastest  version  on Chrome store
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

but  i can not  find “Tamper Fire”  in  the  Dashboard

![image](https://cloud.githubusercontent.com/assets/8925514/7251692/4f85a7f4-e860-11e4-91d2-7fd803f724e4.png)

**Comment by derjanb** [comment]
It was removed at 3.10.3 [1] cause userscripts.org is down anyway. The plan is to maybe create a new extension for this if there is some free time.

[1] http://tampermonkey.net/changelog.php?version=3.10.3&show=dhdg&more=true
