### ISSUE TITLE
JavaScript Strict mode

### ISSUE THREAD

**Issue by uaSad** [derjanb/tampermonkey#213]
```js
// ==UserScript==
// @name         My Fancy New Userscript
// @namespace    http://your.homepage/
// @version      0.1
// @description  enter something useful
// @author       You
// @match        http://*/*
// @grant        none
// ==/UserScript==

(function(a) {
    'use strict';
    a = 'off';
    console.log('strict mode: ' + arguments[0]);
})('on');
```

**Comment by derjanb** [comment]
Unfortunately Tampermonkey is not yet compatible with strict mode userscripts, therefore this mode is disabled by TM.

**Comment by kkot** [comment]
Without strict mode some *es6* stuff don't work so support would be very nice. For example **let** in **for** loop:
```javascript
for (let i = 0; i < 10; i++)
  ;
```
I get:
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by derjanb** [comment]
This should work at TM beta -> http://tampermonkey.net/changelog.php?version=3.12.4699&ext=gcal

**Comment by kkot** [comment]
Now it works, thanks.
