### ISSUE TITLE
Tampermonkey Can Check For Updates WithOut Internet Connection

### ISSUE THREAD

**Issue by r01922090** [derjanb/tampermonkey#215]
I turned off all internet connection for several hours, but Tampermonkey successfully checked for update.

**Comment by derjanb** [comment]
What was the text of the message? Do you mean a update desktop notification 

```"There is an update for '$name$' available"``` or ```"No update found, sry!"```

or if you trigger updates at the options page

```"Operation completed successfully"```?

**Comment by derjanb** [comment]
TM now should not cache neither scripts nor updates -> http://tampermonkey.net/changelog.php?version=4.0.5005&ext=gcal
