### ISSUE TITLE
editor syntax highlight doesn't support es6 template string

### ISSUE THREAD

**Issue by kkot** [derjanb/tampermonkey#217]
ES6 template string works but syntax hightlighting is broken in build-in editor.

![Editor](http://i.imgur.com/QPO3XD8.png)

**Comment by derjanb** [comment]
This should work at TM beta -> http://tampermonkey.net/changelog.php?version=3.12.4699&ext=gcal

**Comment by kkot** [comment]
Now it works, thanks.
