### ISSUE TITLE
Event listener removal bug

### ISSUE THREAD

**Issue by ccd0** [derjanb/tampermonkey#223]
Under certain circumstances, when a script running in Tampermonkey BETA 3.12.4699 calls document.removeEventListener, the wrong listener will be removed.  Demo script:

    // ==UserScript==
    // @name         removeEventListener test
    // @namespace    test
    // @version      0.1
    // @match        http://example.com/
    // ==/UserScript==

    function onNextClick(handler) {
      function cb() {
        document.removeEventListener('click', cb, false);
        handler();
      };
      document.addEventListener('click', cb, false);
    };

    onNextClick(function() {
      console.log('A');
    });
    onNextClick(function() {
      console.log('B');
    });

Expected behavior (as seen with Greasemonkey, Tampermonkey 3.10.109, and just pasting the code into the console):
Clicking the document the first time causes 'A' and 'B' to be logged to the console.  Subsequent clicks do nothing.

Behavior in Tampermonkey BETA 3.12.4699:
Clicking the document causes 'A' to be logged to the console.  'A' continues to be logged to the console with each subsequent click.

Tested in both Debian's Chromium 43.0.2357.65 and in Chrome 43.0.2357.130 on Windows with similar results.

**Comment by derjanb** [comment]
Thanks for your bug report.
Should be fixed now: http://tampermonkey.net/changelog.php?version=3.12.4704&ext=gcal

**Comment by ccd0** [comment]
Thanks, seems to be working.
