### ISSUE TITLE
jQuery UI spinners malfunctioning

### ISSUE THREAD

**Issue by dbarski** [derjanb/tampermonkey#225]
sometimes (not exactly reproducable), a jQuery UI Spinner will continue counting up (or down). jQuery and jQuery UI are added by @require to the page (and then exposed to the page context for debugging purposes).

Here is why I think it is a TM issue and not a jQuery one:

- When manually creating a spinner by executing $("selector").spinner() in the javascript console on the same page and same selector, everything works fine.
- same script works in Firefox+Greasemonkey flawlessly
- in TM Beta, the spinner just goes counting until page reload (ignoring basically everything, even destroying the spinner does not stop this!). In TM stable, sometimes, the spinner continues to count when muse is hovering over it after releasing the mouse button, if no click on any other point was executed

**Comment by derjanb** [comment]
I'm not sure how to test/reproduce this. My test script seems to work fine.

    // ==UserScript==
    // @name         jQuery UI Spinner
    // @namespace    http://your.homepage/
    // @version      0.1
    // @description  enter something useful
    // @require      https://code.jquery.com/jquery-1.10.2.js
    // @require      https://jqueryui.com/resources/demos/external/jquery-mousewheel/jquery.mousewheel.js
    // @require      https://code.jquery.com/ui/1.11.4/jquery-ui.js
    // @match        http://tampermonkey.net/empty.html
    // @grant        unsafeWindow
    // ==/UserScript==

    document.body.innerHTML += '<p><label for="spinner">Select a value:</label><input id="spinner" name="value"></p><p><button id="disable">Toggle disable/enable</button><button id="destroy">Toggle widget</button></p>';

    var spinner = $( "#spinner" ).spinner();

    $( "#disable" ).click(function() {
        if ( spinner.spinner( "option", "disabled" ) ) {
            spinner.spinner( "enable" );
        } else {
            spinner.spinner( "disable" );
        }
    });

    $( "#destroy" ).click(function() {
        if ( spinner.spinner( "instance" ) ) {
            spinner.spinner( "destroy" );
        } else {
            spinner.spinner();
        }
    });

    $( "button" ).button();
