### ISSUE TITLE
TamperMonkey changelog opens on every browser restart

### ISSUE THREAD

**Issue by jmcaffee** [derjanb/tampermonkey#227]
I've tried setting `Show TM update notification` to `Off` and saving but it does not seem to stop the [changelog](http://tampermonkey.net/changelog.php?version=3.11&ext=dhdg&updated=true&old=3.10.109&intr=true) display on the next startup.

After the next startup, `Show TM update notification` is set back to `Open the changlog`

TamperMonkey v3.11
Chromium Version 43.0.2357.130 Ubuntu 14.04

**Comment by derjanb** [comment]
I'm using Ubuntu and Chromium as well and this is working fine here. Do you use incognito mode? Are other changes (i.e. ```Icon Badge Info```) kept?

**Comment by jmcaffee** [comment]
Not using incognito mode...

I rebooted my system and the issue went away so I'm unable to further troubleshoot this.
