### ISSUE TITLE
Option to hide inactive scripts in the popup

### ISSUE THREAD

**Issue by tophf** [derjanb/tampermonkey#229]
When there are many applicable scripts for a page the TM popup becomes crowded and quite inconvenient because of the active/inactive scripts being intertwined.

It'd be very useful to have an option in settings to hide the inactive scripts entirely.
Or maybe a button in the popup to toggle the display of inactive scripts (seems more user-friendly).
Or at least an option to show active scripts grouped together in the popup and inactive scripts at the end of the list.

![popup](https://cloud.githubusercontent.com/assets/1310400/8763407/946df9c0-2da2-11e5-97d3-9a4935515a85.png)

**Comment by derjanb** [comment]
Sounds reasonable...

**Comment by derjanb** [comment]
Done. Thanks for the sugggestion. :)
http://tampermonkey.net/changelog.php?version=3.12.4720&ext=gcal
