### ISSUE TITLE
The toolbar icon dimming question

### ISSUE THREAD

**Issue by tophf** [derjanb/tampermonkey#230]
TM's toolbar icon is dimmed to gray while a page is being loaded and even on a superfast github.com site it takes a few seconds for the original color to show up.

I wonder what is the purpose of this behavior. 

* Provide visual feedback on page load completion? But the browser already indicates that by changing the page refresh icon into `x` (stop) and animating tab's favicon.
* Maybe it might be useful for those who debug something? But it's not very informative nor precise comparing to `console.log`.
* Anyway these constant color changes kinda look distracting.

Here's the code we use in [Stylish-chrome](https://github.com/JasonBarnabe/stylish-chrome) to make its icon never change to the default gray variant during page loads (well, on rare occasions it may still blink for 0.05s or so):

```js
chrome.webNavigation.onCommitted.addListener(webNavigationListener);
chrome.webNavigation.onHistoryStateUpdated.addListener(webNavigationListener);
chrome.webNavigation.onBeforeNavigate.addListener(webNavigationListener);
function webNavigationListener(data) {
	updateIcon({id: data.tabId, url: data.url});
}
```

**Comment by derjanb** [comment]
Fixed at http://tampermonkey.net/changelog.php?version=3.12.4752&ext=gcal
Thanks for reporting.
