### ISSUE TITLE
"Remember me later" at the contribution window

### ISSUE THREAD

**Issue by dinomario10** [derjanb/tampermonkey#231]
At the window that pops up where you introduce yourself, it says "Remember me later", when you possibly meant "Remind me later".

This is not an issue, but a minor typing error.

**Comment by derjanb** [comment]
Thanks a lot. Since I'm a non-native speaker I am always thankful for such hints.

**Comment by derjanb** [comment]
Fixed at TM Beta 3.12.4752. Thanks again!
