### ISSUE TITLE
Script templates for runtime compiled scripts (Coffeescript, ES6, ...?)

### ISSUE THREAD

**Issue by SamHasler** [derjanb/tampermonkey#232]
Could you add [babel](http://babeljs.io/) support so that scripts can use ES6 syntax and be compiled to ES5 for running?

**Comment by derjanb** [comment]
In general this would be possible but there are many problems. You might want version ```1```, the next developer version ```2```. ```2``` is incompatible to ```1```. So what babel version should TM include?

I think the most reasonable approach is to handle it this way: You can write your script in whatever language you want, compile it and then release a userscript with the compiled source.

If this is too inconvenient, then you can also make the code compile at the runtime by using the babel compiler like this:

    // ==UserScript==
    // @name       1ABABBE1
    // @namespace  http://tampermonkey.net/
    // @version    0.1
    // @description shows how to use babel compiler
    // @require    https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js
    // @require    https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser.min.js
    // @include    http://*
    // ==/UserScript==
    
    var inline_src = (<><![CDATA[
    
    /* jshint esnext:true */
    debugger;
    
    let isPrimeFactor = function (factor, number) {
      return number % factor === 0;
    };
    
    let isPrime = function (candidate) {
      if (candidate < 2) {
        return false;
      }
    
      for (let factor = 2; factor <= Math.sqrt(candidate); factor++) {
        if (isPrimeFactor(factor, candidate)) {
          return false;
        }
      }
    
      return true;
    };
    
    let getPrimes = function * (min, max) {
      for (let candidate = min; candidate <= max; candidate++) {
        if (isPrime(candidate)) {
          yield candidate;
        }
      }
    }
    
    for (let prime of getPrimes(100, 150)) {
      console.log(prime);
    }
    
    
    ]]></>).toString();
    
    var c = babel.transform(inline_src);
    eval(c.code);

**Comment by SamHasler** [comment]
Thanks, that's really useful and it would probably have taken me a while to work out how to do that.

Perhaps the templates config could be expanded to be a list of templates that the user could select from and this could be one of them.

(To avoid introducing any extra delay when creating a new script I'd make it default to opening up the whatever the default template was, but with an prompt with buttons or a dropdown for switching to another template. The prompt would disappear as soon as the user started editing the script. This would make it discoverable without getting in the way.)

**Comment by derjanb** [comment]
Sounds great. I'll add this to my TODO list. :)

**Comment by SamHasler** [comment]
I found I had to escape backslashes, so where I had e.g. "\n" I had to do "\\n". If there isn't a way to avoid this then it would be helpful to put a comment into the template so users will expect it.

Also, to get correct line numbers in stack traces I did this:

```
var c = babel.transform('\n'.repeat(14)+inline_src);
```

**Comment by SamHasler** [comment]
NB: see also: https://forum.tampermonkey.net/viewtopic.php?f=21&t=1129

**Comment by derjanb** [comment]
Fixed. :) http://tampermonkey.net/changelog.php?version=3.12.4881&ext=gcal
