### ISSUE TITLE
Cannot trigger the script, but can manually trigger

### ISSUE THREAD

**Issue by willysunny** [derjanb/tampermonkey#233]
Script Page:
https://greasyfork.org/en/scripts/11771-fakku-net-image-list/code

Example of failed page (18+)
https://www.fakku.net/manga/ichiban-chikaku-ni-english/read#page=1

I wrote a simple script for Fakku.net to list all the images, I can execute the script manually (EG: paste the script on the address bar / using bookmarks), however, when I tried to trigger from tampermonkey, it kept returning variable was not defined, as if the variable was added in the page after the code has executed

So ... not sure when is the user script triggered which cause to behave like this intentionally or unexpectedly

**Comment by willysunny** [comment]
Nevermind, I think I find out it's a human error

**Comment by willysunny** [comment]
Never mind, after some digging and some debugging, I think I've come down to the source of the problem.

You see, the site added certain variable into the window.params, which I'm trying to get, however, when I looked at the debug section, I found out that tempermonkey added a header to the beginning of the script that looks like this

    (function(context
    /**/) {
    arguments.callee.__tmid = { uuid: "4732ca77-be05-4297-8d67-3d4bc5ddec51", run_at: "document-idle" };
        with (context) {
    (function(context,window,unsafeWindow,CDATA,uneval,undefined,define,module,console,cloneInto,exportFunction,createObjectIn,TM_addStyle,TM_deleteValue,TM_listValues,TM_getValue,TM_log,TM_registerMenuCommand,TM_unregisterMenuCommand,TM_openInTab,TM_setValue,TM_addValueChangeListener,TM_removeValueChangeListener,TM_xmlhttpRequest,TM_download,TM_setClipboard,TM_getTab,TM_setTab,TM_saveTab,TM_getTabs,TM_installScript,TM_notification,TM_getResourceText,TM_getResourceURL,GM_addStyle,GM_deleteValue,GM_listValues,GM_getValue,GM_addValueChangeListener,GM_removeValueChangeListener,GM_log,GM_registerMenuCommand,GM_unregisterMenuCommand,GM_openInTab,GM_setValue,GM_xmlhttpRequest,GM_download,GM_getResourceText,GM_getResourceURL,GM_notification,GM_installScript,GM_getTab,GM_setTab,GM_saveTab,GM_getTabs,GM_setClipboard,GM_info) {try {

            var fl="";
            for(var i=0;i<window.params.thumbs.length;i++){
            fl+='<img src="'+window.params.thumbs[i].replace('.thumb.','.').replace('thumbs','images')+'"><br />'
            }
            document.write(fl); // outputs the list

    } catch (e) {if (e.message && e.stack) {console.error("ERROR: Execution of script 'Fakku.net image list' failed! " + e.message);console.log(e.stack.replace(/(\\(eval at )?<anonymous>[: ]?)|([\s.]*at TM_mEval[\s\S.]*)/g, ""));} else {console.error(e);}};
    }).apply(context, [,context,context.unsafeWindow,context.CDATA,context.uneval,context.undefined,context.define,context.module,context.console,context.cloneInto,context.exportFunction,context.createObjectIn,context.TM_addStyle,context.TM_deleteValue,context.TM_listValues,context.TM_getValue,context.TM_log,context.TM_registerMenuCommand,context.TM_unregisterMenuCommand,context.TM_openInTab,context.TM_setValue,context.TM_addValueChangeListener,context.TM_removeValueChangeListener,context.TM_xmlhttpRequest,context.TM_download,context.TM_setClipboard,context.TM_getTab,context.TM_setTab,context.TM_saveTab,context.TM_getTabs,context.TM_installScript,context.TM_notification,context.__TMbackref["TM_getResourceText_4732ca77-be05-4297-8d67-3d4bc5ddec51"],context.__TMbackref["TM_getResourceURL_4732ca77-be05-4297-8d67-3d4bc5ddec51"],context.GM_addStyle,context.GM_deleteValue,context.GM_listValues,context.GM_getValue,context.GM_addValueChangeListener,context.GM_removeValueChangeListener,context.GM_log,context.GM_registerMenuCommand,context.GM_unregisterMenuCommand,context.GM_openInTab,context.GM_setValue,context.GM_xmlhttpRequest,context.GM_download,context.GM_getResourceText,context.GM_getResourceURL,context.GM_notification,context.GM_installScript,context.GM_getTab,context.GM_setTab,context.GM_saveTab,context.GM_getTabs,context.GM_setClipboard,context.GM_info]);}

    })

So just in case if you didn't notice, there's a variable named "window" in the function that it created, which just so happen to be in the scope that I was going to call my variable from.

Guess unless the site change their code, I don't think I can do anything about it eh?

**Comment by derjanb** [comment]
You either need to add ```@grant none``` to your script header or use ```unsafeWindow.params``` instead of ```window.params```.

More info: 
http://tampermonkey.net/documentation.php?ext=dhdg#_grant
http://tampermonkey.net/documentation.php?ext=dhdg#unsafeWindow
