### ISSUE TITLE
Debugging in Linux

### ISSUE THREAD

**Issue by trupf** [derjanb/tampermonkey#235]
I'm using Tampermonkey v3.11 with chromium 43.0 under Debian. 
The problem I have:
In debug mode of user scripts the cursor highlighting the next line of code to execute is always 2 lines before the actual code line (see picture, cursor should be in line saying "debugger"). Very confusing.

![debugging](https://cloud.githubusercontent.com/assets/3133318/9698495/5b9ec736-53b9-11e5-85ac-84a824824e71.png)

**Comment by derjanb** [comment]
I've also seen this some time ago, but Chromium 44 and Chrome 47 (both at Ubuntu 14.04) are now working fire here. So I think it was fixed at Chromium 44. 
Sorry, but since it's a Chromium issue there is nothing that I can do for you.
