### ISSUE TITLE
a script crashes in android (dolphin), not chromium.

### ISSUE THREAD

**Issue by bewam** [derjanb/tampermonkey#237]
Hello,
A user of a script I maintain is complaining about crashing on dolphin (android).
The issue can be found on [the script github page: (bewam/fetlife_all_members_-ASL-role-status_filter-#1)](https://github.com/bewam/fetlife_all_members_-ASL-role-status_filter-/issues/1).
As I could not reproduce the configuration he has, I ran it on chromium 45 with 3.11 version, it works like a charm, the script runs as expected.
Do I have to think the tampermonkey for dolphin browser for android is in cause ?
I don't own an android 4.4 to test so I'll try to emulate it. I installed dolphin stuff (thx to xda-dev forum). Where to get an .apk of tampermonkey dolphin outside the market ?
NOTE: the play.store doesn't run on android-x86, account system throws you away... [test it yourself](http://www.android-x86.org/documents/apphowto).
I'd thank 1001 times for a better solution.

**Comment by derjanb** [comment]
I have a android-x86 VM with a working Play Store up and running but please don't ask me where I found the tutorial how to install it. :-)
I made a backup of the current TM Dolphin APK with Astro, I hope it works: 
https://www.dropbox.com/s/5pqtk9so3i2xn4h/TampermonkeyDolphin-release-3.12.4790.apk?dl=0

**Comment by bewam** [comment]
I managed to run the PlayStore on *android-x86* using an existing google profile. I'm still not able to run the script on this platform because of a crash.
In any case, the use of babeljs has solved the problem, thanks.
