### ISSUE TITLE
[beta] strict mode doesn't work "globally"

### ISSUE THREAD

**Issue by 18763C27** [derjanb/tampermonkey#238]
i saw https://github.com/derjanb/tampermonkey/issues/213, the example in it works because it's wrapped in a function expression

```javascript
// ==UserScript==
// @name         strict test
// @include      *
// @grant        none
// ==/UserScript==

"use strict";

console.log(`strict mode: ${ is_strict() ? "on" : "off" }`);

function is_strict () {
	try {
		// throws "SyntaxError: Unexpected eval or arguments in strict mode" in strict mode
		eval("var eval;");
	} catch (e) {
		return true;
	}
}
```

the above script logs `strict mode: off` using tampermonkey but `strict mode: on` using greasemonkey

[mdn says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) `"use strict";` has to be the first statement in a function, but using `debugger` i found a `try` statement before my script which prevents strict mode from working:

```javascript
// beautified and snipped some parts to keep it short
(function(context) {
	with(context) {
		(function(module) {
			"use strict";
			module.apply(/* ... */);
		})(function(/* ... */) {
			try {
				// ==UserScript==
				// ...
				// @grant        none
				// ==/UserScript==
				"use strict"; // has no effect
				debugger;
				// rest of the userscript body
			} catch (e) {
				// ...
			};
		})
	}
})
```

i see the `"use strict";` before `module.apply` but it doesn't seem to get inherited by the userscript

it would "just work" for both strict and sloppy mode scripts if you moved the whole try-catch statement to right after `with(context) {` so that the script could define the first statement in the function as `use strict` if desired

i wanted to make a pull request and fix it for you but the files on this repo are super old

**Comment by derjanb** [comment]
Makes sense. http://tampermonkey.net/changelog.php?version=3.12.4858&ext=gcal
Thanks.
