### ISSUE TITLE
support for strong mode userscripts

### ISSUE THREAD

**Issue by 18763C27** [derjanb/tampermonkey#239]
i found out about [strong mode](https://developers.google.com/v8/experiments#strong-mode) today but tampermonkey doesn't seem to be compatible with it:

    SyntaxError: In strong mode, binding or assigning to 'undefined' is deprecated

you can enable it by lauching chrome with the `--js-flags="--strong-mode"` parameter (or by adding it to your shortcut) and adding `"use strong";` to the beginning of your script like you do with use strict

i get that the feature is still experimental but it'd be nice to have support for it eventually

**Comment by 18763C27** [comment]
making it not pass "undefined" to the script environment (in environment.js) fixes this

**Comment by derjanb** [comment]
There is a new setting to enable strong mode support at the options. In order to see it you need to set the "config mode" to "Advanced", then scroll down to the "Experimental" section. :)

http://tampermonkey.net/changelog.php?version=3.12.4868&ext=gcal
