### ISSUE TITLE
Salted HTTP header while using GM_xmlhttpRequest with Safari

### ISSUE THREAD

**Issue by legnaleurc** [derjanb/tampermonkey#241]
HTTP header in Safari:

```
GET /shortest-url/end-adsession?adSessionId=1b6e61972b20f5d1995fedf2f680114b456bc61b HTTP/1.1
Host: sh.st
Accept-Encoding: gzip, deflate
TM_4e314451-057c-4051-9678-1437a2e5ee4c_Origin: http://sh.st
TM_4e314451-057c-4051-9678-1437a2e5ee4c_Referer: http://sh.st/bwebe
Connection: keep-alive
Accept: application/json, text/javascript
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Accept-Language: en-us
TM_4e314451-057c-4051-9678-1437a2e5ee4c_Host: sh.st
X-Requested-With: XMLHttpRequest

HTTP/1.1 403 Forbidden
Server: nginx
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Powered-By: PHP/5.6.13-0+deb8u1
Set-Cookie: PHPSESSID=bbggi5h3vid76oolhaqmdvuns2; expires=Sun, 11-Oct-2015 11:36:18 GMT; Max-Age=3600; path=/
Cache-Control: no-cache
Date: Sun, 11 Oct 2015 10:36:18 GMT
X-Server-ID: 01.ams
X-UA-Compatible: IE=Edge
Access-Control-Allow-Origin: *
Content-Encoding: gzip
```

Expected as in Chrome:

```
GET /shortest-url/end-adsession?adSessionId=b1bb9b49db8d98854591638b5b9faa5b5a3568b7 HTTP/1.1
Host: sh.st
Connection: keep-alive
Accept: application/json, text/javascript
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: hl=en; PHPSESSID=n1er26j4jp7f965s4gfi8080o6; cookies-enable=1; _ga=GA1.2.541938380.1391782347; _gat=1
Referer: http://sh.st/bwebe
Origin: http://sh.st

HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Transfer-Encoding: chunked
X-Powered-By: PHP/5.6.13-0+deb8u1
Cache-Control: no-cache
Date: Sun, 11 Oct 2015 10:39:59 GMT
Set-Cookie: referrer_url=http%3A%2F%2Fsh.st%2Fbwebe; expires=Mon, 12-Oct-2015 10:39:59 GMT; Max-Age=86400; path=/; httponly
X-Server-ID: 04.ams
X-UA-Compatible: IE=Edge
Access-Control-Allow-Origin: *
```

Note `Referer`, `Origin` and `Host` in the header.

**Comment by derjanb** [comment]
I fixed it - unfortunately not in the right way. Like all Webkit(Blink)-based browsers Safari doesn't allow some of the headers of xmlHttpRequests to be set. In order to workaround this TM uses an API called chrome.webRequest [1], but Safari has no equivalent. So the fix is to only rely on Safari's capabilities of setting the allowed headers (only ```referrer```) and not to use the salted ones at all.

http://tampermonkey.net/changelog.php?version=3.12.4868&ext=G3XV

[1] https://developer.chrome.com/extensions/webRequest

**Comment by legnaleurc** [comment]
Hmm ... I don't see `Referer` in the updated version though.
It still is a nice fix anyway, thank you.

**Comment by pankajnarola1995** [comment]
> I fixed it - unfortunately not in the right way. Like all Webkit(Blink)-based browsers Safari doesn't allow some of the headers of xmlHttpRequests to be set. In order to workaround this TM uses an API called chrome.webRequest [1], but Safari has no equivalent. So the fix is to only rely on Safari's capabilities of setting the allowed headers (only `referrer`) and not to use the salted ones at all.
> 
> http://tampermonkey.net/changelog.php?version=3.12.4868&ext=G3XV
> 
> [1] https://developer.chrome.com/extensions/webRequest

Hello, @derjanb I think I have almost a similar problem with safari browser.

i have the below code

```
// @grant        GM_xmlhttpRequest

GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            responseType: 'json',
            onload: function (responseCurrentUser) {})
```
This works very fine in crome and firefox box in safari it gives this error...

```
response: Object

error: "Unauthorized"

error_description: ""

Object Prototype

responseHeaders: "access-control-expose-headers: Location
↵cache-control: no-cache, no-store, no-transform, must-revalidate
↵content-encoding: UTF-8…"

responseText: 

responseType: "json"

responseXML: 

status: 401

statusText: ""
```
The same code is working well for chrome and firefox.

I don't understand why? I tried to google it but not found answer.. so could you please tell me where I'm wrong? or what I'm missing? According to your answer, I don't use any headers with api call so what should I check?
and the same API Url if I run directly into safari browser then it returns the value what I expect.. 🤔
