### ISSUE TITLE
Autocomplete and lint in the editor

### ISSUE THREAD

**Issue by tophf** [derjanb/tampermonkey#243]
Autocomplete is an awesome functionality and in CodeMirror it is provided by [show-hint.js addon](http://codemirror.net/doc/manual.html#addon_show-hint) (see also the [demo  page](http://codemirror.net/demo/complete.html)).

```html
<link rel="stylesheet" href="codemirror/addon/hint/show-hint.css">
<script src="codemirror/addon/hint/show-hint.js"></script>
<script src="codemirror/addon/hint/javascript-hint.js"></script>
```
```js
CodeMirror.keyMap.pcDefault["Ctrl-Space"] = "autocomplete"; // used by "sublime" keymap on PC via fallthrough
CodeMirror.keyMap.macDefault["Alt-Space"] = "autocomplete"; // OSX uses Ctrl-Space/Cmd-Space for something else
```

Linting while editing is also awesome: [lint.js addon](http://codemirror.net/doc/manual.html#addon_lint) (see also the [demo page](http://codemirror.net/demo/lint.html)). Requires [JSHint](https://github.com/jshint/jshint). Also, now that script templates are supported you may try adding CoffeeScript lint too, although I don't know how good it is.

```html
<link rel="stylesheet" href="codemirror/addon/lint/lint.css" />
<script src="jshint/jshint.js"></script>
<script src="codemirror/addon/lint/lint.js"></script>
<script src="codemirror/addon/lint/coffeescript-lint.js"></script>
<script src="codemirror/addon/lint/javascript-lint.js"></script>
```
```js
var cm = CodeMirror(someElement, {
    lint: true,
    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter", "CodeMirror-lint-markers"],
});
```

**Comment by derjanb** [comment]
Implemented! :) CoffeeScript support is still missing, but I'll take a look at this later.

http://tampermonkey.net/changelog.php?version=3.13.4923&ext=gcal

**Comment by tophf** [comment]
I've noticed the Autocomplete addon doesn't autoinsert the text in case it's a single suggestion in the list. I think the usual behaviour is to not show the menu and just insert the text. 

To enable it I would use something like this: `CodeMirror.defaults.hintOptions = {completeSingle: true}` or `<CodeMirror instance>.options.hintOptions = {completeSingle: true}` - hintOptions are null by default.

**Comment by derjanb** [comment]
I explicitly disabled this behavior. If you for example type this:

    var remVar = null;
    rem

and then run the autocompletion ```removeEventListener``` would be chosen. But maybe ```remVar``` was expected. Now the user has to delete many characters in order to fix this. I think this is more annoying than pressing Enter if you're happy with the suggested completion.

I'll take a look at Tern later. If it works well, then auto-completion list should be much better,

**Comment by tophf** [comment]
>Now the user has to delete many characters in order to fix this

No, only a single `Z` key of `Ctrl-Z` sequence (Ctrl is still pressed as part of `Ctrl-Space`).

**Comment by zanetu** [comment]
[**@derjanb**](https://github.com/derjanb) commented on [Nov 30, 2015, 3:28 PM EST](https://github.com/derjanb/tampermonkey/issues/243#issuecomment-160752276 "2015-11-30T20:28:44Z - Replied by Github Comment Enhancer"):
> Implemented! :) CoffeeScript support is still missing, but I'll take a look at this later.
> 
> [http://tampermonkey.net/changelog.php?version=3.13.4923&amp;ext=gcal](http://tampermonkey.net/changelog.php?version=3.13.4923&amp;ext=gcal)

It there a way disable linting? The editor looks terrible for semicolon-less scripts.

**Comment by derjanb** [comment]
> It there a way to disable linting? The editor looks terrible for semicolon-less scripts.

Sure, just disable the option ```Automatic syntax check on typing```.

Another solution is to configure JSHint to not moan about semicolons by adding 
```/* jshint asi:true */```
to the top of the script.

**Comment by zanetu** [comment]
[**@derjanb**](https://github.com/derjanb) commented on [Dec 2, 2015, 5:07 AM EST](https://github.com/derjanb/tampermonkey/issues/243#issuecomment-161246038 "2015-12-02T10:07:21Z - Replied by Github Comment Enhancer"):
> > It there a way to disable linting? The editor looks terrible for semicolon-less scripts.
> 
> Sure, just disable the option `Automatic syntax check on typing`.
> 
> Another solution is to configure JSHint to not moan about semicolons by adding   
> 
> `/* jshint asi:true */`  
> 
> to the top of the script.

Got it. Thanks.

**Comment by derjanb** [comment]
> No, only a single Z key of Ctrl-Z sequence (Ctrl is still pressed as part of Ctrl-Space).

Implemented. :)

**Comment by Sentero-esp12** [comment]
How to enable auto-complete in Tampermonkey? Is it an option in the settings?

**Comment by derjanb** [comment]
Simply open Tampermonkey's options page, select the "Help" tab and search for "autocomplete".
