### ISSUE TITLE
Tampermonkey 2016 Genuine?

### ISSUE THREAD

**Issue by Watilin** [derjanb/tampermonkey#246]
Hi,

on Chrome Web Store, on 1st position when searching for “Tampermonkey”, there's an addon named “Tampermonkey 2016” provided by `entercrx.com`. Screenshots are the same but the description has been changed.
I was wondering if this is related to the real Tampermonkey or if it's some sort of despicable click farming/SEO manipulation.

**Comment by derjanb** [comment]
> Your abuse report was submitted successfully.

Thanks a lot for reporting.
