### ISSUE TITLE
All UserScripts gone after Chrome Update! :(

### ISSUE THREAD

**Issue by metawops** [derjanb/tampermonkey#247]
I just HAD to update Chrome from v44 to v46 here on my office Windows 7 PC.
Unfortunately, now all my UserScripts are gone which is a desaster. :(
This never happened to me at home so I never had the idea to make backups of my scripts outside of Chrome/TamperMonkey. :( (Will certainly do now!)

The solutions I found for this problem didn't work so far (entering ``localStorage.setItem('TM_version', null); chrome.runtime.reload();`` in the background console).

Any other ideas? Are my scripts really gone (would be fatal)?

Thanks so much for any help,
Stefan.

**Comment by derjanb** [comment]
Do you have a backup of the Chrome profile folder? If you can try to recover the scripts using this Python script: https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0

**Comment by metawops** [comment]
Ugh! No other way?
Even IF I find a Chrome profile folder ... I don't have Python on my office PC & am not allowed to install software (no admin). :frowning:

**Comment by derjanb** [comment]
Unfortunately not. If Chrome wipes or corrupts the extension database there is not much the extension can do.
You can also copy the extension folder and try it at home. You just have to point the Python script to this copy.

**Comment by metawops** [comment]
I see. Several days of work down the drain. :frowning: 
So what did go wrong? I need a bit of technical details to go to the IT support guys and shout on them...

**Comment by metawops** [comment]
Would it be possible to save my user scripts somewhere with my Google account? So when I install Chrome for the first time on a new machine and log into my Google account and all my Chrome extensions get loaded ... my TM user scripts would get loaded, too, from the Google ... cloud?

**Comment by derjanb** [comment]
> So what did go wrong? 

I don't know. It seems like somehow Chrome lost the extension storage.

> Would it be possible to save my user scripts somewhere with my Google account?

If you enabled Tampermonkey's sync option, then you should be able to retrieve all scripts again. But only those that are installed from a publicly accessible URL. See this page for more infos: http://tampermonkey.net/faq#Q105

**Comment by eapo** [comment]
i have the same problem after the Tampermonkey extension crashed in Chrome on Windows 7. the python script doesn't work on windows and i spent too much time searching for the files on my computer.. gives me headache.  :(
