### ISSUE TITLE
Intercept reverse search hotkey in editor

### ISSUE THREAD

**Issue by tobbez** [derjanb/tampermonkey#248]
Currently only the forward search hotkey (F3) is intercepted in the code editor, but not the reverse search hotkey (Shift+F3).

If you press the reverse search hotkey Chrome's builtin search is triggered instead of Tampermonkey's.

**Comment by derjanb** [comment]
Fixed. :) http://tampermonkey.net/changelog.php?version=3.13.4923&ext=gcal
