### ISSUE TITLE
Global strict mode is still broken

### ISSUE THREAD

**Issue by line0** [derjanb/tampermonkey#249]
Strict mode issues were already addressed in #213 and #238 and it's still broken when the user script has any require directives. You can easily confirm it by adding any `@require` to the test script from #238. Tested with v3.13.4899 Beta.

On top of that, enabling script debugging also kills "use strict";.

**Comment by derjanb** [comment]
Unfortunately I see no way to make this work in all circumstances without adding something that is incompatible to old scripts and/or script managers. But if you need strict mode, then you can easily work-around this by wrapping your code into a self-executing anonymous function. 
However, I'll change the script template accordingly.

If you don't publish you script, then you can set TM's ```strict mode``` setting to ```Always``` to enforce strict mode for all scripts.

**Comment by CoffeeFlux** [comment]
Ignoring the require issue, you can't even fix that script debugging kills it?

**Comment by derjanb** [comment]
TM now is doing some simple parsing to add the debugger statement after all comments and '/"use strict"/' statements. However there is a fair chance that it's not working correctly at every script.
