### ISSUE TITLE
window.focus failing when @grant is not none

### ISSUE THREAD

**Issue by ccd0** [derjanb/tampermonkey#253]
The following code works (switches back to the tab when the notification is clicked) in Greasemonkey, when pasted into the console, and in Tampermonkey with the `@grant none`, but it doesn't work in Tampermonkey with `@grant` other than none.  It throws a "TypeError: Illegal invocation" error.  Tested in Chrome 47.0.2526.73 with Tampermonkey 3.12.

    // ==UserScript==
    // @name         window.focus bug
    // @namespace    test
    // @match        http://www.example.com/
    // @grant        GM_getValue
    // ==/UserScript==
     
    Notification.requestPermission(function() {
      var x = new Notification('hello world');
      x.addEventListener('click', function() {
        try {
            window.focus();
        } catch(e) {
            console.log(e);
        }
      }, false);
    });

**Comment by derjanb** [comment]
This is already fixed at the beta version. A new stable will be released soon.

**Comment by derjanb** [comment]
Fixed. http://tampermonkey.net/changelog.php?version=3.12.58&ext=dhdg
