### ISSUE TITLE
Beta 4.0.5008 hangs trying to display Linkify++ code in dashboard

### ISSUE THREAD

**Issue by tophf** [derjanb/tampermonkey#257]
1. Install [Linkify++](https://greasyfork.org/scripts/4255-linkify-plus-plus/)
2. Go to TM dashboard
3. Click the installed userscript name

**Comment by derjanb** [comment]
Thanks for this one. :)

http://tampermonkey.net/changelog.php?version=4.0.5022&ext=gcal
